import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.css";
import "./styles/style.scss";

import ReduxProvider from "@/shared/provider/ReduxProvider";
import Dial from "@/lol/Dial";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kazakh Republic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>{children}</ReduxProvider>
        
      </body>
    </html>
  );
}
